# Generated by Django 3.0.5 on 2020-04-30 04:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200430_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
